

### GENERAL

# reload config file
bind r \
	 source-file ~/.tmux.conf \; \
	 display-message "Configuration reloaded"


# time for using command without Prefix after the first command (in miliseconds)
# reset when a command is sent during this time interval
set -g repeat-time 1000


# Default using some vi keys in command mode
# set status-keys vi

### WINDOW

# set the base index for windows to 1 instead of 0
# g stand for global, means that it applies to all sessions
set -g base-index 1

# using repeatable navigating through windows
unbind n
unbind p
bind -r n select-window -t :+
bind -r p select-window -t :-


### PANE

# set the base index for pane to 1
# w stand for window
set -w -g pane-base-index 1 
# more resonable pane creation
unbind '"'
unbind %

bind / split-window -h
bind - split-window -v

# switch panes 
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

# resize panes
bind -r c-h resize-pane -L 5
bind -r c-l resize-pane -R 5
bind -r c-k resize-pane -U 5
bind -r c-j resize-pane -D 5

# swap panes
#


### COPY MODE
# using vi-like visual mode for copy mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel



### CUSTOMIZE LOOKS OF TMUX

# customize status line
set -g status-style fg=black,bg=green
set -g window-status-current-style fg=black,bg=white


# Colors for pane borders
set -w -g pane-border-style fg=white,bg=black
set -w -g pane-active-border-style fg=green,bg=black

# Status line right side: 08:44 13-Sep
set -g status-right "%R %b-%d"

# Refresh the status line every minute
set -g status-interval 60

# Enable activity alerts
set -w -g monitor-activity on
set -w -g visual-activity off


