
unbind '"'
unbind %

bind / split-window -h
bind - split-window -v

# reload config file
bind c-r source-file ~/.tmux.conf


### PANE
# switch panes 
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

# swap panes



set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

